version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: CrmContainer
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crm_database
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crm-network

  app:
    image: openjdk:17
    container_name: spring-crm-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crm_database
      SPRING_DATASOURCE_USERNAME: crm_user
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - crm-network
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run

networks:
  crm-network:
    driver: bridge

volumes:
  db_data: